export enum RegisterModuleErrorCodes {
  UNKNOWN = 'REGISTER_MODULE_UNKNOWN',
  DB_ERROR = 'DB_ERROR',
  USERNAME_ALREADY_USED = 'USERNAME_ALREADY_USED',
  EMAIL_ALREADY_USED = 'EMAIL_ALREADY_USED',
}
